services:
  postgres:
    container_name: postgres
    image: postgres:13.6
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pizza_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 5555:5555
      - 8080:8080
    volumes:
      - ./:/app
    healthcheck:
      # Check if server is running and accepting requests
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
